import { Albert_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/providers/ReactQueryProvider";
import Header from "@/components/navigation/header/header";
import Footer from "@/components/navigation/footer/footer";
import { Toaster } from "react-hot-toast";

const albertSans = Albert_Sans({
  family: "Albert Sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-albert-sans",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${albertSans.variable} antialiased `}>
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />
          <Header />
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
